// source: google/ads/googleads/v3/common/offline_user_data.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.object.extend(proto, google_protobuf_wrappers_pb);
var google_api_annotations_pb = require('../../../../../google/api/annotations_pb.js');
goog.object.extend(proto, google_api_annotations_pb);
goog.exportSymbol('proto.google.ads.googleads.v3.common.CustomerMatchUserListMetadata', null, global);
goog.exportSymbol('proto.google.ads.googleads.v3.common.OfflineUserAddressInfo', null, global);
goog.exportSymbol('proto.google.ads.googleads.v3.common.StoreAttribute', null, global);
goog.exportSymbol('proto.google.ads.googleads.v3.common.StoreSalesMetadata', null, global);
goog.exportSymbol('proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata', null, global);
goog.exportSymbol('proto.google.ads.googleads.v3.common.TransactionAttribute', null, global);
goog.exportSymbol('proto.google.ads.googleads.v3.common.UserData', null, global);
goog.exportSymbol('proto.google.ads.googleads.v3.common.UserIdentifier', null, global);
goog.exportSymbol('proto.google.ads.googleads.v3.common.UserIdentifier.IdentifierCase', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.ads.googleads.v3.common.OfflineUserAddressInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.ads.googleads.v3.common.OfflineUserAddressInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.ads.googleads.v3.common.OfflineUserAddressInfo.displayName = 'proto.google.ads.googleads.v3.common.OfflineUserAddressInfo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.ads.googleads.v3.common.UserIdentifier = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.google.ads.googleads.v3.common.UserIdentifier.oneofGroups_);
};
goog.inherits(proto.google.ads.googleads.v3.common.UserIdentifier, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.ads.googleads.v3.common.UserIdentifier.displayName = 'proto.google.ads.googleads.v3.common.UserIdentifier';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.ads.googleads.v3.common.TransactionAttribute = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.ads.googleads.v3.common.TransactionAttribute, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.ads.googleads.v3.common.TransactionAttribute.displayName = 'proto.google.ads.googleads.v3.common.TransactionAttribute';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.ads.googleads.v3.common.StoreAttribute = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.ads.googleads.v3.common.StoreAttribute, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.ads.googleads.v3.common.StoreAttribute.displayName = 'proto.google.ads.googleads.v3.common.StoreAttribute';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.ads.googleads.v3.common.UserData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.ads.googleads.v3.common.UserData.repeatedFields_, null);
};
goog.inherits(proto.google.ads.googleads.v3.common.UserData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.ads.googleads.v3.common.UserData.displayName = 'proto.google.ads.googleads.v3.common.UserData';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.ads.googleads.v3.common.CustomerMatchUserListMetadata = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.ads.googleads.v3.common.CustomerMatchUserListMetadata, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.ads.googleads.v3.common.CustomerMatchUserListMetadata.displayName = 'proto.google.ads.googleads.v3.common.CustomerMatchUserListMetadata';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.ads.googleads.v3.common.StoreSalesMetadata = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.ads.googleads.v3.common.StoreSalesMetadata, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.ads.googleads.v3.common.StoreSalesMetadata.displayName = 'proto.google.ads.googleads.v3.common.StoreSalesMetadata';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata.displayName = 'proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.ads.googleads.v3.common.OfflineUserAddressInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.google.ads.googleads.v3.common.OfflineUserAddressInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.ads.googleads.v3.common.OfflineUserAddressInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.ads.googleads.v3.common.OfflineUserAddressInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    hashedFirstName: (f = msg.getHashedFirstName()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    hashedLastName: (f = msg.getHashedLastName()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    city: (f = msg.getCity()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    state: (f = msg.getState()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    countryCode: (f = msg.getCountryCode()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    postalCode: (f = msg.getPostalCode()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.ads.googleads.v3.common.OfflineUserAddressInfo}
 */
proto.google.ads.googleads.v3.common.OfflineUserAddressInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.ads.googleads.v3.common.OfflineUserAddressInfo;
  return proto.google.ads.googleads.v3.common.OfflineUserAddressInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.ads.googleads.v3.common.OfflineUserAddressInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.ads.googleads.v3.common.OfflineUserAddressInfo}
 */
proto.google.ads.googleads.v3.common.OfflineUserAddressInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setHashedFirstName(value);
      break;
    case 2:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setHashedLastName(value);
      break;
    case 3:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setCity(value);
      break;
    case 4:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setState(value);
      break;
    case 5:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setCountryCode(value);
      break;
    case 6:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setPostalCode(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.ads.googleads.v3.common.OfflineUserAddressInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.ads.googleads.v3.common.OfflineUserAddressInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.ads.googleads.v3.common.OfflineUserAddressInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.ads.googleads.v3.common.OfflineUserAddressInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHashedFirstName();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getHashedLastName();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getCity();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getState();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getCountryCode();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getPostalCode();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.StringValue hashed_first_name = 1;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.google.ads.googleads.v3.common.OfflineUserAddressInfo.prototype.getHashedFirstName = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 1));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.google.ads.googleads.v3.common.OfflineUserAddressInfo} returns this
*/
proto.google.ads.googleads.v3.common.OfflineUserAddressInfo.prototype.setHashedFirstName = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.ads.googleads.v3.common.OfflineUserAddressInfo} returns this
 */
proto.google.ads.googleads.v3.common.OfflineUserAddressInfo.prototype.clearHashedFirstName = function() {
  return this.setHashedFirstName(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.ads.googleads.v3.common.OfflineUserAddressInfo.prototype.hasHashedFirstName = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.StringValue hashed_last_name = 2;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.google.ads.googleads.v3.common.OfflineUserAddressInfo.prototype.getHashedLastName = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 2));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.google.ads.googleads.v3.common.OfflineUserAddressInfo} returns this
*/
proto.google.ads.googleads.v3.common.OfflineUserAddressInfo.prototype.setHashedLastName = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.ads.googleads.v3.common.OfflineUserAddressInfo} returns this
 */
proto.google.ads.googleads.v3.common.OfflineUserAddressInfo.prototype.clearHashedLastName = function() {
  return this.setHashedLastName(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.ads.googleads.v3.common.OfflineUserAddressInfo.prototype.hasHashedLastName = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.StringValue city = 3;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.google.ads.googleads.v3.common.OfflineUserAddressInfo.prototype.getCity = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 3));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.google.ads.googleads.v3.common.OfflineUserAddressInfo} returns this
*/
proto.google.ads.googleads.v3.common.OfflineUserAddressInfo.prototype.setCity = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.ads.googleads.v3.common.OfflineUserAddressInfo} returns this
 */
proto.google.ads.googleads.v3.common.OfflineUserAddressInfo.prototype.clearCity = function() {
  return this.setCity(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.ads.googleads.v3.common.OfflineUserAddressInfo.prototype.hasCity = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional google.protobuf.StringValue state = 4;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.google.ads.googleads.v3.common.OfflineUserAddressInfo.prototype.getState = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 4));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.google.ads.googleads.v3.common.OfflineUserAddressInfo} returns this
*/
proto.google.ads.googleads.v3.common.OfflineUserAddressInfo.prototype.setState = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.ads.googleads.v3.common.OfflineUserAddressInfo} returns this
 */
proto.google.ads.googleads.v3.common.OfflineUserAddressInfo.prototype.clearState = function() {
  return this.setState(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.ads.googleads.v3.common.OfflineUserAddressInfo.prototype.hasState = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional google.protobuf.StringValue country_code = 5;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.google.ads.googleads.v3.common.OfflineUserAddressInfo.prototype.getCountryCode = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 5));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.google.ads.googleads.v3.common.OfflineUserAddressInfo} returns this
*/
proto.google.ads.googleads.v3.common.OfflineUserAddressInfo.prototype.setCountryCode = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.ads.googleads.v3.common.OfflineUserAddressInfo} returns this
 */
proto.google.ads.googleads.v3.common.OfflineUserAddressInfo.prototype.clearCountryCode = function() {
  return this.setCountryCode(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.ads.googleads.v3.common.OfflineUserAddressInfo.prototype.hasCountryCode = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional google.protobuf.StringValue postal_code = 6;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.google.ads.googleads.v3.common.OfflineUserAddressInfo.prototype.getPostalCode = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 6));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.google.ads.googleads.v3.common.OfflineUserAddressInfo} returns this
*/
proto.google.ads.googleads.v3.common.OfflineUserAddressInfo.prototype.setPostalCode = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.ads.googleads.v3.common.OfflineUserAddressInfo} returns this
 */
proto.google.ads.googleads.v3.common.OfflineUserAddressInfo.prototype.clearPostalCode = function() {
  return this.setPostalCode(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.ads.googleads.v3.common.OfflineUserAddressInfo.prototype.hasPostalCode = function() {
  return jspb.Message.getField(this, 6) != null;
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.google.ads.googleads.v3.common.UserIdentifier.oneofGroups_ = [[1,2,3,4,5]];

/**
 * @enum {number}
 */
proto.google.ads.googleads.v3.common.UserIdentifier.IdentifierCase = {
  IDENTIFIER_NOT_SET: 0,
  HASHED_EMAIL: 1,
  HASHED_PHONE_NUMBER: 2,
  MOBILE_ID: 3,
  THIRD_PARTY_USER_ID: 4,
  ADDRESS_INFO: 5
};

/**
 * @return {proto.google.ads.googleads.v3.common.UserIdentifier.IdentifierCase}
 */
proto.google.ads.googleads.v3.common.UserIdentifier.prototype.getIdentifierCase = function() {
  return /** @type {proto.google.ads.googleads.v3.common.UserIdentifier.IdentifierCase} */(jspb.Message.computeOneofCase(this, proto.google.ads.googleads.v3.common.UserIdentifier.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.ads.googleads.v3.common.UserIdentifier.prototype.toObject = function(opt_includeInstance) {
  return proto.google.ads.googleads.v3.common.UserIdentifier.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.ads.googleads.v3.common.UserIdentifier} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.ads.googleads.v3.common.UserIdentifier.toObject = function(includeInstance, msg) {
  var f, obj = {
    hashedEmail: (f = msg.getHashedEmail()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    hashedPhoneNumber: (f = msg.getHashedPhoneNumber()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    mobileId: (f = msg.getMobileId()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    thirdPartyUserId: (f = msg.getThirdPartyUserId()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    addressInfo: (f = msg.getAddressInfo()) && proto.google.ads.googleads.v3.common.OfflineUserAddressInfo.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.ads.googleads.v3.common.UserIdentifier}
 */
proto.google.ads.googleads.v3.common.UserIdentifier.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.ads.googleads.v3.common.UserIdentifier;
  return proto.google.ads.googleads.v3.common.UserIdentifier.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.ads.googleads.v3.common.UserIdentifier} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.ads.googleads.v3.common.UserIdentifier}
 */
proto.google.ads.googleads.v3.common.UserIdentifier.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setHashedEmail(value);
      break;
    case 2:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setHashedPhoneNumber(value);
      break;
    case 3:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setMobileId(value);
      break;
    case 4:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setThirdPartyUserId(value);
      break;
    case 5:
      var value = new proto.google.ads.googleads.v3.common.OfflineUserAddressInfo;
      reader.readMessage(value,proto.google.ads.googleads.v3.common.OfflineUserAddressInfo.deserializeBinaryFromReader);
      msg.setAddressInfo(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.ads.googleads.v3.common.UserIdentifier.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.ads.googleads.v3.common.UserIdentifier.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.ads.googleads.v3.common.UserIdentifier} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.ads.googleads.v3.common.UserIdentifier.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHashedEmail();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getHashedPhoneNumber();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getMobileId();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getThirdPartyUserId();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getAddressInfo();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.google.ads.googleads.v3.common.OfflineUserAddressInfo.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.StringValue hashed_email = 1;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.google.ads.googleads.v3.common.UserIdentifier.prototype.getHashedEmail = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 1));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.google.ads.googleads.v3.common.UserIdentifier} returns this
*/
proto.google.ads.googleads.v3.common.UserIdentifier.prototype.setHashedEmail = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.google.ads.googleads.v3.common.UserIdentifier.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.ads.googleads.v3.common.UserIdentifier} returns this
 */
proto.google.ads.googleads.v3.common.UserIdentifier.prototype.clearHashedEmail = function() {
  return this.setHashedEmail(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.ads.googleads.v3.common.UserIdentifier.prototype.hasHashedEmail = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.StringValue hashed_phone_number = 2;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.google.ads.googleads.v3.common.UserIdentifier.prototype.getHashedPhoneNumber = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 2));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.google.ads.googleads.v3.common.UserIdentifier} returns this
*/
proto.google.ads.googleads.v3.common.UserIdentifier.prototype.setHashedPhoneNumber = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.google.ads.googleads.v3.common.UserIdentifier.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.ads.googleads.v3.common.UserIdentifier} returns this
 */
proto.google.ads.googleads.v3.common.UserIdentifier.prototype.clearHashedPhoneNumber = function() {
  return this.setHashedPhoneNumber(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.ads.googleads.v3.common.UserIdentifier.prototype.hasHashedPhoneNumber = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.StringValue mobile_id = 3;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.google.ads.googleads.v3.common.UserIdentifier.prototype.getMobileId = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 3));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.google.ads.googleads.v3.common.UserIdentifier} returns this
*/
proto.google.ads.googleads.v3.common.UserIdentifier.prototype.setMobileId = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.google.ads.googleads.v3.common.UserIdentifier.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.ads.googleads.v3.common.UserIdentifier} returns this
 */
proto.google.ads.googleads.v3.common.UserIdentifier.prototype.clearMobileId = function() {
  return this.setMobileId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.ads.googleads.v3.common.UserIdentifier.prototype.hasMobileId = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional google.protobuf.StringValue third_party_user_id = 4;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.google.ads.googleads.v3.common.UserIdentifier.prototype.getThirdPartyUserId = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 4));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.google.ads.googleads.v3.common.UserIdentifier} returns this
*/
proto.google.ads.googleads.v3.common.UserIdentifier.prototype.setThirdPartyUserId = function(value) {
  return jspb.Message.setOneofWrapperField(this, 4, proto.google.ads.googleads.v3.common.UserIdentifier.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.ads.googleads.v3.common.UserIdentifier} returns this
 */
proto.google.ads.googleads.v3.common.UserIdentifier.prototype.clearThirdPartyUserId = function() {
  return this.setThirdPartyUserId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.ads.googleads.v3.common.UserIdentifier.prototype.hasThirdPartyUserId = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional OfflineUserAddressInfo address_info = 5;
 * @return {?proto.google.ads.googleads.v3.common.OfflineUserAddressInfo}
 */
proto.google.ads.googleads.v3.common.UserIdentifier.prototype.getAddressInfo = function() {
  return /** @type{?proto.google.ads.googleads.v3.common.OfflineUserAddressInfo} */ (
    jspb.Message.getWrapperField(this, proto.google.ads.googleads.v3.common.OfflineUserAddressInfo, 5));
};


/**
 * @param {?proto.google.ads.googleads.v3.common.OfflineUserAddressInfo|undefined} value
 * @return {!proto.google.ads.googleads.v3.common.UserIdentifier} returns this
*/
proto.google.ads.googleads.v3.common.UserIdentifier.prototype.setAddressInfo = function(value) {
  return jspb.Message.setOneofWrapperField(this, 5, proto.google.ads.googleads.v3.common.UserIdentifier.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.ads.googleads.v3.common.UserIdentifier} returns this
 */
proto.google.ads.googleads.v3.common.UserIdentifier.prototype.clearAddressInfo = function() {
  return this.setAddressInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.ads.googleads.v3.common.UserIdentifier.prototype.hasAddressInfo = function() {
  return jspb.Message.getField(this, 5) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.ads.googleads.v3.common.TransactionAttribute.prototype.toObject = function(opt_includeInstance) {
  return proto.google.ads.googleads.v3.common.TransactionAttribute.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.ads.googleads.v3.common.TransactionAttribute} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.ads.googleads.v3.common.TransactionAttribute.toObject = function(includeInstance, msg) {
  var f, obj = {
    transactionDateTime: (f = msg.getTransactionDateTime()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    transactionAmountMicros: (f = msg.getTransactionAmountMicros()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    currencyCode: (f = msg.getCurrencyCode()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    conversionAction: (f = msg.getConversionAction()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    orderId: (f = msg.getOrderId()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    storeAttribute: (f = msg.getStoreAttribute()) && proto.google.ads.googleads.v3.common.StoreAttribute.toObject(includeInstance, f),
    customValue: (f = msg.getCustomValue()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.ads.googleads.v3.common.TransactionAttribute}
 */
proto.google.ads.googleads.v3.common.TransactionAttribute.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.ads.googleads.v3.common.TransactionAttribute;
  return proto.google.ads.googleads.v3.common.TransactionAttribute.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.ads.googleads.v3.common.TransactionAttribute} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.ads.googleads.v3.common.TransactionAttribute}
 */
proto.google.ads.googleads.v3.common.TransactionAttribute.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setTransactionDateTime(value);
      break;
    case 2:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setTransactionAmountMicros(value);
      break;
    case 3:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setCurrencyCode(value);
      break;
    case 4:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setConversionAction(value);
      break;
    case 5:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setOrderId(value);
      break;
    case 6:
      var value = new proto.google.ads.googleads.v3.common.StoreAttribute;
      reader.readMessage(value,proto.google.ads.googleads.v3.common.StoreAttribute.deserializeBinaryFromReader);
      msg.setStoreAttribute(value);
      break;
    case 7:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setCustomValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.ads.googleads.v3.common.TransactionAttribute.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.ads.googleads.v3.common.TransactionAttribute.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.ads.googleads.v3.common.TransactionAttribute} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.ads.googleads.v3.common.TransactionAttribute.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTransactionDateTime();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getTransactionAmountMicros();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getCurrencyCode();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getConversionAction();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getOrderId();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getStoreAttribute();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.google.ads.googleads.v3.common.StoreAttribute.serializeBinaryToWriter
    );
  }
  f = message.getCustomValue();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.StringValue transaction_date_time = 1;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.google.ads.googleads.v3.common.TransactionAttribute.prototype.getTransactionDateTime = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 1));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.google.ads.googleads.v3.common.TransactionAttribute} returns this
*/
proto.google.ads.googleads.v3.common.TransactionAttribute.prototype.setTransactionDateTime = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.ads.googleads.v3.common.TransactionAttribute} returns this
 */
proto.google.ads.googleads.v3.common.TransactionAttribute.prototype.clearTransactionDateTime = function() {
  return this.setTransactionDateTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.ads.googleads.v3.common.TransactionAttribute.prototype.hasTransactionDateTime = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.DoubleValue transaction_amount_micros = 2;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.google.ads.googleads.v3.common.TransactionAttribute.prototype.getTransactionAmountMicros = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 2));
};


/**
 * @param {?proto.google.protobuf.DoubleValue|undefined} value
 * @return {!proto.google.ads.googleads.v3.common.TransactionAttribute} returns this
*/
proto.google.ads.googleads.v3.common.TransactionAttribute.prototype.setTransactionAmountMicros = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.ads.googleads.v3.common.TransactionAttribute} returns this
 */
proto.google.ads.googleads.v3.common.TransactionAttribute.prototype.clearTransactionAmountMicros = function() {
  return this.setTransactionAmountMicros(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.ads.googleads.v3.common.TransactionAttribute.prototype.hasTransactionAmountMicros = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.StringValue currency_code = 3;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.google.ads.googleads.v3.common.TransactionAttribute.prototype.getCurrencyCode = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 3));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.google.ads.googleads.v3.common.TransactionAttribute} returns this
*/
proto.google.ads.googleads.v3.common.TransactionAttribute.prototype.setCurrencyCode = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.ads.googleads.v3.common.TransactionAttribute} returns this
 */
proto.google.ads.googleads.v3.common.TransactionAttribute.prototype.clearCurrencyCode = function() {
  return this.setCurrencyCode(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.ads.googleads.v3.common.TransactionAttribute.prototype.hasCurrencyCode = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional google.protobuf.StringValue conversion_action = 4;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.google.ads.googleads.v3.common.TransactionAttribute.prototype.getConversionAction = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 4));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.google.ads.googleads.v3.common.TransactionAttribute} returns this
*/
proto.google.ads.googleads.v3.common.TransactionAttribute.prototype.setConversionAction = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.ads.googleads.v3.common.TransactionAttribute} returns this
 */
proto.google.ads.googleads.v3.common.TransactionAttribute.prototype.clearConversionAction = function() {
  return this.setConversionAction(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.ads.googleads.v3.common.TransactionAttribute.prototype.hasConversionAction = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional google.protobuf.StringValue order_id = 5;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.google.ads.googleads.v3.common.TransactionAttribute.prototype.getOrderId = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 5));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.google.ads.googleads.v3.common.TransactionAttribute} returns this
*/
proto.google.ads.googleads.v3.common.TransactionAttribute.prototype.setOrderId = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.ads.googleads.v3.common.TransactionAttribute} returns this
 */
proto.google.ads.googleads.v3.common.TransactionAttribute.prototype.clearOrderId = function() {
  return this.setOrderId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.ads.googleads.v3.common.TransactionAttribute.prototype.hasOrderId = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional StoreAttribute store_attribute = 6;
 * @return {?proto.google.ads.googleads.v3.common.StoreAttribute}
 */
proto.google.ads.googleads.v3.common.TransactionAttribute.prototype.getStoreAttribute = function() {
  return /** @type{?proto.google.ads.googleads.v3.common.StoreAttribute} */ (
    jspb.Message.getWrapperField(this, proto.google.ads.googleads.v3.common.StoreAttribute, 6));
};


/**
 * @param {?proto.google.ads.googleads.v3.common.StoreAttribute|undefined} value
 * @return {!proto.google.ads.googleads.v3.common.TransactionAttribute} returns this
*/
proto.google.ads.googleads.v3.common.TransactionAttribute.prototype.setStoreAttribute = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.ads.googleads.v3.common.TransactionAttribute} returns this
 */
proto.google.ads.googleads.v3.common.TransactionAttribute.prototype.clearStoreAttribute = function() {
  return this.setStoreAttribute(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.ads.googleads.v3.common.TransactionAttribute.prototype.hasStoreAttribute = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional google.protobuf.StringValue custom_value = 7;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.google.ads.googleads.v3.common.TransactionAttribute.prototype.getCustomValue = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 7));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.google.ads.googleads.v3.common.TransactionAttribute} returns this
*/
proto.google.ads.googleads.v3.common.TransactionAttribute.prototype.setCustomValue = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.ads.googleads.v3.common.TransactionAttribute} returns this
 */
proto.google.ads.googleads.v3.common.TransactionAttribute.prototype.clearCustomValue = function() {
  return this.setCustomValue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.ads.googleads.v3.common.TransactionAttribute.prototype.hasCustomValue = function() {
  return jspb.Message.getField(this, 7) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.ads.googleads.v3.common.StoreAttribute.prototype.toObject = function(opt_includeInstance) {
  return proto.google.ads.googleads.v3.common.StoreAttribute.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.ads.googleads.v3.common.StoreAttribute} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.ads.googleads.v3.common.StoreAttribute.toObject = function(includeInstance, msg) {
  var f, obj = {
    storeCode: (f = msg.getStoreCode()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.ads.googleads.v3.common.StoreAttribute}
 */
proto.google.ads.googleads.v3.common.StoreAttribute.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.ads.googleads.v3.common.StoreAttribute;
  return proto.google.ads.googleads.v3.common.StoreAttribute.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.ads.googleads.v3.common.StoreAttribute} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.ads.googleads.v3.common.StoreAttribute}
 */
proto.google.ads.googleads.v3.common.StoreAttribute.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setStoreCode(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.ads.googleads.v3.common.StoreAttribute.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.ads.googleads.v3.common.StoreAttribute.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.ads.googleads.v3.common.StoreAttribute} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.ads.googleads.v3.common.StoreAttribute.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStoreCode();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.StringValue store_code = 1;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.google.ads.googleads.v3.common.StoreAttribute.prototype.getStoreCode = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 1));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.google.ads.googleads.v3.common.StoreAttribute} returns this
*/
proto.google.ads.googleads.v3.common.StoreAttribute.prototype.setStoreCode = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.ads.googleads.v3.common.StoreAttribute} returns this
 */
proto.google.ads.googleads.v3.common.StoreAttribute.prototype.clearStoreCode = function() {
  return this.setStoreCode(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.ads.googleads.v3.common.StoreAttribute.prototype.hasStoreCode = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.ads.googleads.v3.common.UserData.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.ads.googleads.v3.common.UserData.prototype.toObject = function(opt_includeInstance) {
  return proto.google.ads.googleads.v3.common.UserData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.ads.googleads.v3.common.UserData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.ads.googleads.v3.common.UserData.toObject = function(includeInstance, msg) {
  var f, obj = {
    userIdentifiersList: jspb.Message.toObjectList(msg.getUserIdentifiersList(),
    proto.google.ads.googleads.v3.common.UserIdentifier.toObject, includeInstance),
    transactionAttribute: (f = msg.getTransactionAttribute()) && proto.google.ads.googleads.v3.common.TransactionAttribute.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.ads.googleads.v3.common.UserData}
 */
proto.google.ads.googleads.v3.common.UserData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.ads.googleads.v3.common.UserData;
  return proto.google.ads.googleads.v3.common.UserData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.ads.googleads.v3.common.UserData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.ads.googleads.v3.common.UserData}
 */
proto.google.ads.googleads.v3.common.UserData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.google.ads.googleads.v3.common.UserIdentifier;
      reader.readMessage(value,proto.google.ads.googleads.v3.common.UserIdentifier.deserializeBinaryFromReader);
      msg.addUserIdentifiers(value);
      break;
    case 2:
      var value = new proto.google.ads.googleads.v3.common.TransactionAttribute;
      reader.readMessage(value,proto.google.ads.googleads.v3.common.TransactionAttribute.deserializeBinaryFromReader);
      msg.setTransactionAttribute(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.ads.googleads.v3.common.UserData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.ads.googleads.v3.common.UserData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.ads.googleads.v3.common.UserData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.ads.googleads.v3.common.UserData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUserIdentifiersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.google.ads.googleads.v3.common.UserIdentifier.serializeBinaryToWriter
    );
  }
  f = message.getTransactionAttribute();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.google.ads.googleads.v3.common.TransactionAttribute.serializeBinaryToWriter
    );
  }
};


/**
 * repeated UserIdentifier user_identifiers = 1;
 * @return {!Array<!proto.google.ads.googleads.v3.common.UserIdentifier>}
 */
proto.google.ads.googleads.v3.common.UserData.prototype.getUserIdentifiersList = function() {
  return /** @type{!Array<!proto.google.ads.googleads.v3.common.UserIdentifier>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.ads.googleads.v3.common.UserIdentifier, 1));
};


/**
 * @param {!Array<!proto.google.ads.googleads.v3.common.UserIdentifier>} value
 * @return {!proto.google.ads.googleads.v3.common.UserData} returns this
*/
proto.google.ads.googleads.v3.common.UserData.prototype.setUserIdentifiersList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.google.ads.googleads.v3.common.UserIdentifier=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.ads.googleads.v3.common.UserIdentifier}
 */
proto.google.ads.googleads.v3.common.UserData.prototype.addUserIdentifiers = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.google.ads.googleads.v3.common.UserIdentifier, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.ads.googleads.v3.common.UserData} returns this
 */
proto.google.ads.googleads.v3.common.UserData.prototype.clearUserIdentifiersList = function() {
  return this.setUserIdentifiersList([]);
};


/**
 * optional TransactionAttribute transaction_attribute = 2;
 * @return {?proto.google.ads.googleads.v3.common.TransactionAttribute}
 */
proto.google.ads.googleads.v3.common.UserData.prototype.getTransactionAttribute = function() {
  return /** @type{?proto.google.ads.googleads.v3.common.TransactionAttribute} */ (
    jspb.Message.getWrapperField(this, proto.google.ads.googleads.v3.common.TransactionAttribute, 2));
};


/**
 * @param {?proto.google.ads.googleads.v3.common.TransactionAttribute|undefined} value
 * @return {!proto.google.ads.googleads.v3.common.UserData} returns this
*/
proto.google.ads.googleads.v3.common.UserData.prototype.setTransactionAttribute = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.ads.googleads.v3.common.UserData} returns this
 */
proto.google.ads.googleads.v3.common.UserData.prototype.clearTransactionAttribute = function() {
  return this.setTransactionAttribute(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.ads.googleads.v3.common.UserData.prototype.hasTransactionAttribute = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.ads.googleads.v3.common.CustomerMatchUserListMetadata.prototype.toObject = function(opt_includeInstance) {
  return proto.google.ads.googleads.v3.common.CustomerMatchUserListMetadata.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.ads.googleads.v3.common.CustomerMatchUserListMetadata} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.ads.googleads.v3.common.CustomerMatchUserListMetadata.toObject = function(includeInstance, msg) {
  var f, obj = {
    userList: (f = msg.getUserList()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.ads.googleads.v3.common.CustomerMatchUserListMetadata}
 */
proto.google.ads.googleads.v3.common.CustomerMatchUserListMetadata.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.ads.googleads.v3.common.CustomerMatchUserListMetadata;
  return proto.google.ads.googleads.v3.common.CustomerMatchUserListMetadata.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.ads.googleads.v3.common.CustomerMatchUserListMetadata} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.ads.googleads.v3.common.CustomerMatchUserListMetadata}
 */
proto.google.ads.googleads.v3.common.CustomerMatchUserListMetadata.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setUserList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.ads.googleads.v3.common.CustomerMatchUserListMetadata.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.ads.googleads.v3.common.CustomerMatchUserListMetadata.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.ads.googleads.v3.common.CustomerMatchUserListMetadata} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.ads.googleads.v3.common.CustomerMatchUserListMetadata.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUserList();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.StringValue user_list = 1;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.google.ads.googleads.v3.common.CustomerMatchUserListMetadata.prototype.getUserList = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 1));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.google.ads.googleads.v3.common.CustomerMatchUserListMetadata} returns this
*/
proto.google.ads.googleads.v3.common.CustomerMatchUserListMetadata.prototype.setUserList = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.ads.googleads.v3.common.CustomerMatchUserListMetadata} returns this
 */
proto.google.ads.googleads.v3.common.CustomerMatchUserListMetadata.prototype.clearUserList = function() {
  return this.setUserList(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.ads.googleads.v3.common.CustomerMatchUserListMetadata.prototype.hasUserList = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.ads.googleads.v3.common.StoreSalesMetadata.prototype.toObject = function(opt_includeInstance) {
  return proto.google.ads.googleads.v3.common.StoreSalesMetadata.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.ads.googleads.v3.common.StoreSalesMetadata} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.ads.googleads.v3.common.StoreSalesMetadata.toObject = function(includeInstance, msg) {
  var f, obj = {
    loyaltyFraction: (f = msg.getLoyaltyFraction()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    transactionUploadFraction: (f = msg.getTransactionUploadFraction()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    customKey: (f = msg.getCustomKey()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    thirdPartyMetadata: (f = msg.getThirdPartyMetadata()) && proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.ads.googleads.v3.common.StoreSalesMetadata}
 */
proto.google.ads.googleads.v3.common.StoreSalesMetadata.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.ads.googleads.v3.common.StoreSalesMetadata;
  return proto.google.ads.googleads.v3.common.StoreSalesMetadata.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.ads.googleads.v3.common.StoreSalesMetadata} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.ads.googleads.v3.common.StoreSalesMetadata}
 */
proto.google.ads.googleads.v3.common.StoreSalesMetadata.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setLoyaltyFraction(value);
      break;
    case 2:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setTransactionUploadFraction(value);
      break;
    case 4:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setCustomKey(value);
      break;
    case 3:
      var value = new proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata;
      reader.readMessage(value,proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata.deserializeBinaryFromReader);
      msg.setThirdPartyMetadata(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.ads.googleads.v3.common.StoreSalesMetadata.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.ads.googleads.v3.common.StoreSalesMetadata.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.ads.googleads.v3.common.StoreSalesMetadata} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.ads.googleads.v3.common.StoreSalesMetadata.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLoyaltyFraction();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getTransactionUploadFraction();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getCustomKey();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getThirdPartyMetadata();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.DoubleValue loyalty_fraction = 1;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.google.ads.googleads.v3.common.StoreSalesMetadata.prototype.getLoyaltyFraction = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 1));
};


/**
 * @param {?proto.google.protobuf.DoubleValue|undefined} value
 * @return {!proto.google.ads.googleads.v3.common.StoreSalesMetadata} returns this
*/
proto.google.ads.googleads.v3.common.StoreSalesMetadata.prototype.setLoyaltyFraction = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.ads.googleads.v3.common.StoreSalesMetadata} returns this
 */
proto.google.ads.googleads.v3.common.StoreSalesMetadata.prototype.clearLoyaltyFraction = function() {
  return this.setLoyaltyFraction(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.ads.googleads.v3.common.StoreSalesMetadata.prototype.hasLoyaltyFraction = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.DoubleValue transaction_upload_fraction = 2;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.google.ads.googleads.v3.common.StoreSalesMetadata.prototype.getTransactionUploadFraction = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 2));
};


/**
 * @param {?proto.google.protobuf.DoubleValue|undefined} value
 * @return {!proto.google.ads.googleads.v3.common.StoreSalesMetadata} returns this
*/
proto.google.ads.googleads.v3.common.StoreSalesMetadata.prototype.setTransactionUploadFraction = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.ads.googleads.v3.common.StoreSalesMetadata} returns this
 */
proto.google.ads.googleads.v3.common.StoreSalesMetadata.prototype.clearTransactionUploadFraction = function() {
  return this.setTransactionUploadFraction(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.ads.googleads.v3.common.StoreSalesMetadata.prototype.hasTransactionUploadFraction = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.StringValue custom_key = 4;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.google.ads.googleads.v3.common.StoreSalesMetadata.prototype.getCustomKey = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 4));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.google.ads.googleads.v3.common.StoreSalesMetadata} returns this
*/
proto.google.ads.googleads.v3.common.StoreSalesMetadata.prototype.setCustomKey = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.ads.googleads.v3.common.StoreSalesMetadata} returns this
 */
proto.google.ads.googleads.v3.common.StoreSalesMetadata.prototype.clearCustomKey = function() {
  return this.setCustomKey(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.ads.googleads.v3.common.StoreSalesMetadata.prototype.hasCustomKey = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional StoreSalesThirdPartyMetadata third_party_metadata = 3;
 * @return {?proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata}
 */
proto.google.ads.googleads.v3.common.StoreSalesMetadata.prototype.getThirdPartyMetadata = function() {
  return /** @type{?proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata} */ (
    jspb.Message.getWrapperField(this, proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata, 3));
};


/**
 * @param {?proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata|undefined} value
 * @return {!proto.google.ads.googleads.v3.common.StoreSalesMetadata} returns this
*/
proto.google.ads.googleads.v3.common.StoreSalesMetadata.prototype.setThirdPartyMetadata = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.ads.googleads.v3.common.StoreSalesMetadata} returns this
 */
proto.google.ads.googleads.v3.common.StoreSalesMetadata.prototype.clearThirdPartyMetadata = function() {
  return this.setThirdPartyMetadata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.ads.googleads.v3.common.StoreSalesMetadata.prototype.hasThirdPartyMetadata = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata.prototype.toObject = function(opt_includeInstance) {
  return proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata.toObject = function(includeInstance, msg) {
  var f, obj = {
    advertiserUploadDateTime: (f = msg.getAdvertiserUploadDateTime()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    validTransactionFraction: (f = msg.getValidTransactionFraction()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    partnerMatchFraction: (f = msg.getPartnerMatchFraction()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    partnerUploadFraction: (f = msg.getPartnerUploadFraction()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    bridgeMapVersionId: (f = msg.getBridgeMapVersionId()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    partnerId: (f = msg.getPartnerId()) && google_protobuf_wrappers_pb.Int64Value.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata}
 */
proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata;
  return proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata}
 */
proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setAdvertiserUploadDateTime(value);
      break;
    case 2:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setValidTransactionFraction(value);
      break;
    case 3:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setPartnerMatchFraction(value);
      break;
    case 4:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setPartnerUploadFraction(value);
      break;
    case 5:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setBridgeMapVersionId(value);
      break;
    case 6:
      var value = new google_protobuf_wrappers_pb.Int64Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.Int64Value.deserializeBinaryFromReader);
      msg.setPartnerId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAdvertiserUploadDateTime();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getValidTransactionFraction();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getPartnerMatchFraction();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getPartnerUploadFraction();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getBridgeMapVersionId();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getPartnerId();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_wrappers_pb.Int64Value.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.StringValue advertiser_upload_date_time = 1;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata.prototype.getAdvertiserUploadDateTime = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 1));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata} returns this
*/
proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata.prototype.setAdvertiserUploadDateTime = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata} returns this
 */
proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata.prototype.clearAdvertiserUploadDateTime = function() {
  return this.setAdvertiserUploadDateTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata.prototype.hasAdvertiserUploadDateTime = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.DoubleValue valid_transaction_fraction = 2;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata.prototype.getValidTransactionFraction = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 2));
};


/**
 * @param {?proto.google.protobuf.DoubleValue|undefined} value
 * @return {!proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata} returns this
*/
proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata.prototype.setValidTransactionFraction = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata} returns this
 */
proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata.prototype.clearValidTransactionFraction = function() {
  return this.setValidTransactionFraction(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata.prototype.hasValidTransactionFraction = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.DoubleValue partner_match_fraction = 3;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata.prototype.getPartnerMatchFraction = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 3));
};


/**
 * @param {?proto.google.protobuf.DoubleValue|undefined} value
 * @return {!proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata} returns this
*/
proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata.prototype.setPartnerMatchFraction = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata} returns this
 */
proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata.prototype.clearPartnerMatchFraction = function() {
  return this.setPartnerMatchFraction(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata.prototype.hasPartnerMatchFraction = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional google.protobuf.DoubleValue partner_upload_fraction = 4;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata.prototype.getPartnerUploadFraction = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 4));
};


/**
 * @param {?proto.google.protobuf.DoubleValue|undefined} value
 * @return {!proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata} returns this
*/
proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata.prototype.setPartnerUploadFraction = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata} returns this
 */
proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata.prototype.clearPartnerUploadFraction = function() {
  return this.setPartnerUploadFraction(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata.prototype.hasPartnerUploadFraction = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional google.protobuf.StringValue bridge_map_version_id = 5;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata.prototype.getBridgeMapVersionId = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 5));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata} returns this
*/
proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata.prototype.setBridgeMapVersionId = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata} returns this
 */
proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata.prototype.clearBridgeMapVersionId = function() {
  return this.setBridgeMapVersionId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata.prototype.hasBridgeMapVersionId = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional google.protobuf.Int64Value partner_id = 6;
 * @return {?proto.google.protobuf.Int64Value}
 */
proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata.prototype.getPartnerId = function() {
  return /** @type{?proto.google.protobuf.Int64Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.Int64Value, 6));
};


/**
 * @param {?proto.google.protobuf.Int64Value|undefined} value
 * @return {!proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata} returns this
*/
proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata.prototype.setPartnerId = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata} returns this
 */
proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata.prototype.clearPartnerId = function() {
  return this.setPartnerId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.ads.googleads.v3.common.StoreSalesThirdPartyMetadata.prototype.hasPartnerId = function() {
  return jspb.Message.getField(this, 6) != null;
};


goog.object.extend(exports, proto.google.ads.googleads.v3.common);
