// source: google/ads/googleads/v3/services/offline_user_data_job_service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_ads_googleads_v3_common_offline_user_data_pb = require('../../../../../google/ads/googleads/v3/common/offline_user_data_pb.js');
goog.object.extend(proto, google_ads_googleads_v3_common_offline_user_data_pb);
var google_ads_googleads_v3_resources_offline_user_data_job_pb = require('../../../../../google/ads/googleads/v3/resources/offline_user_data_job_pb.js');
goog.object.extend(proto, google_ads_googleads_v3_resources_offline_user_data_job_pb);
var google_api_annotations_pb = require('../../../../../google/api/annotations_pb.js');
goog.object.extend(proto, google_api_annotations_pb);
var google_api_client_pb = require('../../../../../google/api/client_pb.js');
goog.object.extend(proto, google_api_client_pb);
var google_api_field_behavior_pb = require('../../../../../google/api/field_behavior_pb.js');
goog.object.extend(proto, google_api_field_behavior_pb);
var google_api_resource_pb = require('../../../../../google/api/resource_pb.js');
goog.object.extend(proto, google_api_resource_pb);
var google_longrunning_operations_pb = require('../../../../../google/longrunning/operations_pb.js');
goog.object.extend(proto, google_longrunning_operations_pb);
var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.object.extend(proto, google_protobuf_wrappers_pb);
var google_rpc_status_pb = require('../../../../../google/rpc/status_pb.js');
goog.object.extend(proto, google_rpc_status_pb);
goog.exportSymbol('proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsRequest', null, global);
goog.exportSymbol('proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsResponse', null, global);
goog.exportSymbol('proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobRequest', null, global);
goog.exportSymbol('proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobResponse', null, global);
goog.exportSymbol('proto.google.ads.googleads.v3.services.GetOfflineUserDataJobRequest', null, global);
goog.exportSymbol('proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation', null, global);
goog.exportSymbol('proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation.OperationCase', null, global);
goog.exportSymbol('proto.google.ads.googleads.v3.services.RunOfflineUserDataJobRequest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobRequest.displayName = 'proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobResponse.displayName = 'proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.ads.googleads.v3.services.GetOfflineUserDataJobRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.ads.googleads.v3.services.GetOfflineUserDataJobRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.ads.googleads.v3.services.GetOfflineUserDataJobRequest.displayName = 'proto.google.ads.googleads.v3.services.GetOfflineUserDataJobRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.ads.googleads.v3.services.RunOfflineUserDataJobRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.ads.googleads.v3.services.RunOfflineUserDataJobRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.ads.googleads.v3.services.RunOfflineUserDataJobRequest.displayName = 'proto.google.ads.googleads.v3.services.RunOfflineUserDataJobRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsRequest.repeatedFields_, null);
};
goog.inherits(proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsRequest.displayName = 'proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation.oneofGroups_);
};
goog.inherits(proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation.displayName = 'proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsResponse.displayName = 'proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    customerId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    job: (f = msg.getJob()) && google_ads_googleads_v3_resources_offline_user_data_job_pb.OfflineUserDataJob.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobRequest}
 */
proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobRequest;
  return proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobRequest}
 */
proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCustomerId(value);
      break;
    case 2:
      var value = new google_ads_googleads_v3_resources_offline_user_data_job_pb.OfflineUserDataJob;
      reader.readMessage(value,google_ads_googleads_v3_resources_offline_user_data_job_pb.OfflineUserDataJob.deserializeBinaryFromReader);
      msg.setJob(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCustomerId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getJob();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_ads_googleads_v3_resources_offline_user_data_job_pb.OfflineUserDataJob.serializeBinaryToWriter
    );
  }
};


/**
 * optional string customer_id = 1;
 * @return {string}
 */
proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobRequest.prototype.getCustomerId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobRequest} returns this
 */
proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobRequest.prototype.setCustomerId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional google.ads.googleads.v3.resources.OfflineUserDataJob job = 2;
 * @return {?proto.google.ads.googleads.v3.resources.OfflineUserDataJob}
 */
proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobRequest.prototype.getJob = function() {
  return /** @type{?proto.google.ads.googleads.v3.resources.OfflineUserDataJob} */ (
    jspb.Message.getWrapperField(this, google_ads_googleads_v3_resources_offline_user_data_job_pb.OfflineUserDataJob, 2));
};


/**
 * @param {?proto.google.ads.googleads.v3.resources.OfflineUserDataJob|undefined} value
 * @return {!proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobRequest} returns this
*/
proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobRequest.prototype.setJob = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobRequest} returns this
 */
proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobRequest.prototype.clearJob = function() {
  return this.setJob(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobRequest.prototype.hasJob = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    resourceName: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobResponse}
 */
proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobResponse;
  return proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobResponse}
 */
proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setResourceName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getResourceName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string resource_name = 1;
 * @return {string}
 */
proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobResponse.prototype.getResourceName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobResponse} returns this
 */
proto.google.ads.googleads.v3.services.CreateOfflineUserDataJobResponse.prototype.setResourceName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.ads.googleads.v3.services.GetOfflineUserDataJobRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.google.ads.googleads.v3.services.GetOfflineUserDataJobRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.ads.googleads.v3.services.GetOfflineUserDataJobRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.ads.googleads.v3.services.GetOfflineUserDataJobRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    resourceName: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.ads.googleads.v3.services.GetOfflineUserDataJobRequest}
 */
proto.google.ads.googleads.v3.services.GetOfflineUserDataJobRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.ads.googleads.v3.services.GetOfflineUserDataJobRequest;
  return proto.google.ads.googleads.v3.services.GetOfflineUserDataJobRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.ads.googleads.v3.services.GetOfflineUserDataJobRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.ads.googleads.v3.services.GetOfflineUserDataJobRequest}
 */
proto.google.ads.googleads.v3.services.GetOfflineUserDataJobRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setResourceName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.ads.googleads.v3.services.GetOfflineUserDataJobRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.ads.googleads.v3.services.GetOfflineUserDataJobRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.ads.googleads.v3.services.GetOfflineUserDataJobRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.ads.googleads.v3.services.GetOfflineUserDataJobRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getResourceName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string resource_name = 1;
 * @return {string}
 */
proto.google.ads.googleads.v3.services.GetOfflineUserDataJobRequest.prototype.getResourceName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.ads.googleads.v3.services.GetOfflineUserDataJobRequest} returns this
 */
proto.google.ads.googleads.v3.services.GetOfflineUserDataJobRequest.prototype.setResourceName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.ads.googleads.v3.services.RunOfflineUserDataJobRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.google.ads.googleads.v3.services.RunOfflineUserDataJobRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.ads.googleads.v3.services.RunOfflineUserDataJobRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.ads.googleads.v3.services.RunOfflineUserDataJobRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    resourceName: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.ads.googleads.v3.services.RunOfflineUserDataJobRequest}
 */
proto.google.ads.googleads.v3.services.RunOfflineUserDataJobRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.ads.googleads.v3.services.RunOfflineUserDataJobRequest;
  return proto.google.ads.googleads.v3.services.RunOfflineUserDataJobRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.ads.googleads.v3.services.RunOfflineUserDataJobRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.ads.googleads.v3.services.RunOfflineUserDataJobRequest}
 */
proto.google.ads.googleads.v3.services.RunOfflineUserDataJobRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setResourceName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.ads.googleads.v3.services.RunOfflineUserDataJobRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.ads.googleads.v3.services.RunOfflineUserDataJobRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.ads.googleads.v3.services.RunOfflineUserDataJobRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.ads.googleads.v3.services.RunOfflineUserDataJobRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getResourceName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string resource_name = 1;
 * @return {string}
 */
proto.google.ads.googleads.v3.services.RunOfflineUserDataJobRequest.prototype.getResourceName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.ads.googleads.v3.services.RunOfflineUserDataJobRequest} returns this
 */
proto.google.ads.googleads.v3.services.RunOfflineUserDataJobRequest.prototype.setResourceName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsRequest.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    resourceName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    enablePartialFailure: (f = msg.getEnablePartialFailure()) && google_protobuf_wrappers_pb.BoolValue.toObject(includeInstance, f),
    operationsList: jspb.Message.toObjectList(msg.getOperationsList(),
    proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsRequest}
 */
proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsRequest;
  return proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsRequest}
 */
proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setResourceName(value);
      break;
    case 2:
      var value = new google_protobuf_wrappers_pb.BoolValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.BoolValue.deserializeBinaryFromReader);
      msg.setEnablePartialFailure(value);
      break;
    case 3:
      var value = new proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation;
      reader.readMessage(value,proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation.deserializeBinaryFromReader);
      msg.addOperations(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getResourceName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getEnablePartialFailure();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_wrappers_pb.BoolValue.serializeBinaryToWriter
    );
  }
  f = message.getOperationsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation.serializeBinaryToWriter
    );
  }
};


/**
 * optional string resource_name = 1;
 * @return {string}
 */
proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsRequest.prototype.getResourceName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsRequest} returns this
 */
proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsRequest.prototype.setResourceName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional google.protobuf.BoolValue enable_partial_failure = 2;
 * @return {?proto.google.protobuf.BoolValue}
 */
proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsRequest.prototype.getEnablePartialFailure = function() {
  return /** @type{?proto.google.protobuf.BoolValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.BoolValue, 2));
};


/**
 * @param {?proto.google.protobuf.BoolValue|undefined} value
 * @return {!proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsRequest} returns this
*/
proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsRequest.prototype.setEnablePartialFailure = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsRequest} returns this
 */
proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsRequest.prototype.clearEnablePartialFailure = function() {
  return this.setEnablePartialFailure(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsRequest.prototype.hasEnablePartialFailure = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated OfflineUserDataJobOperation operations = 3;
 * @return {!Array<!proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation>}
 */
proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsRequest.prototype.getOperationsList = function() {
  return /** @type{!Array<!proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation, 3));
};


/**
 * @param {!Array<!proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation>} value
 * @return {!proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsRequest} returns this
*/
proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsRequest.prototype.setOperationsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation}
 */
proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsRequest.prototype.addOperations = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsRequest} returns this
 */
proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsRequest.prototype.clearOperationsList = function() {
  return this.setOperationsList([]);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation.oneofGroups_ = [[1,2,3]];

/**
 * @enum {number}
 */
proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation.OperationCase = {
  OPERATION_NOT_SET: 0,
  CREATE: 1,
  REMOVE: 2,
  REMOVE_ALL: 3
};

/**
 * @return {proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation.OperationCase}
 */
proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation.prototype.getOperationCase = function() {
  return /** @type {proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation.OperationCase} */(jspb.Message.computeOneofCase(this, proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation.prototype.toObject = function(opt_includeInstance) {
  return proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation.toObject = function(includeInstance, msg) {
  var f, obj = {
    create: (f = msg.getCreate()) && google_ads_googleads_v3_common_offline_user_data_pb.UserData.toObject(includeInstance, f),
    remove: (f = msg.getRemove()) && google_ads_googleads_v3_common_offline_user_data_pb.UserData.toObject(includeInstance, f),
    removeAll: jspb.Message.getBooleanFieldWithDefault(msg, 3, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation}
 */
proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation;
  return proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation}
 */
proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_ads_googleads_v3_common_offline_user_data_pb.UserData;
      reader.readMessage(value,google_ads_googleads_v3_common_offline_user_data_pb.UserData.deserializeBinaryFromReader);
      msg.setCreate(value);
      break;
    case 2:
      var value = new google_ads_googleads_v3_common_offline_user_data_pb.UserData;
      reader.readMessage(value,google_ads_googleads_v3_common_offline_user_data_pb.UserData.deserializeBinaryFromReader);
      msg.setRemove(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRemoveAll(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCreate();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_ads_googleads_v3_common_offline_user_data_pb.UserData.serializeBinaryToWriter
    );
  }
  f = message.getRemove();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_ads_googleads_v3_common_offline_user_data_pb.UserData.serializeBinaryToWriter
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeBool(
      3,
      f
    );
  }
};


/**
 * optional google.ads.googleads.v3.common.UserData create = 1;
 * @return {?proto.google.ads.googleads.v3.common.UserData}
 */
proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation.prototype.getCreate = function() {
  return /** @type{?proto.google.ads.googleads.v3.common.UserData} */ (
    jspb.Message.getWrapperField(this, google_ads_googleads_v3_common_offline_user_data_pb.UserData, 1));
};


/**
 * @param {?proto.google.ads.googleads.v3.common.UserData|undefined} value
 * @return {!proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation} returns this
*/
proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation.prototype.setCreate = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation} returns this
 */
proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation.prototype.clearCreate = function() {
  return this.setCreate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation.prototype.hasCreate = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.ads.googleads.v3.common.UserData remove = 2;
 * @return {?proto.google.ads.googleads.v3.common.UserData}
 */
proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation.prototype.getRemove = function() {
  return /** @type{?proto.google.ads.googleads.v3.common.UserData} */ (
    jspb.Message.getWrapperField(this, google_ads_googleads_v3_common_offline_user_data_pb.UserData, 2));
};


/**
 * @param {?proto.google.ads.googleads.v3.common.UserData|undefined} value
 * @return {!proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation} returns this
*/
proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation.prototype.setRemove = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation} returns this
 */
proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation.prototype.clearRemove = function() {
  return this.setRemove(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation.prototype.hasRemove = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional bool remove_all = 3;
 * @return {boolean}
 */
proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation.prototype.getRemoveAll = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation} returns this
 */
proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation.prototype.setRemoveAll = function(value) {
  return jspb.Message.setOneofField(this, 3, proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation} returns this
 */
proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation.prototype.clearRemoveAll = function() {
  return jspb.Message.setOneofField(this, 3, proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.ads.googleads.v3.services.OfflineUserDataJobOperation.prototype.hasRemoveAll = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    partialFailureError: (f = msg.getPartialFailureError()) && google_rpc_status_pb.Status.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsResponse}
 */
proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsResponse;
  return proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsResponse}
 */
proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_rpc_status_pb.Status;
      reader.readMessage(value,google_rpc_status_pb.Status.deserializeBinaryFromReader);
      msg.setPartialFailureError(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPartialFailureError();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_rpc_status_pb.Status.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.rpc.Status partial_failure_error = 1;
 * @return {?proto.google.rpc.Status}
 */
proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsResponse.prototype.getPartialFailureError = function() {
  return /** @type{?proto.google.rpc.Status} */ (
    jspb.Message.getWrapperField(this, google_rpc_status_pb.Status, 1));
};


/**
 * @param {?proto.google.rpc.Status|undefined} value
 * @return {!proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsResponse} returns this
*/
proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsResponse.prototype.setPartialFailureError = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsResponse} returns this
 */
proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsResponse.prototype.clearPartialFailureError = function() {
  return this.setPartialFailureError(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.ads.googleads.v3.services.AddOfflineUserDataJobOperationsResponse.prototype.hasPartialFailureError = function() {
  return jspb.Message.getField(this, 1) != null;
};


goog.object.extend(exports, proto.google.ads.googleads.v3.services);
