// source: google/ads/googleads/v3/resources/offline_user_data_job.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_ads_googleads_v3_common_offline_user_data_pb = require('../../../../../google/ads/googleads/v3/common/offline_user_data_pb.js');
goog.object.extend(proto, google_ads_googleads_v3_common_offline_user_data_pb);
var google_ads_googleads_v3_enums_offline_user_data_job_failure_reason_pb = require('../../../../../google/ads/googleads/v3/enums/offline_user_data_job_failure_reason_pb.js');
goog.object.extend(proto, google_ads_googleads_v3_enums_offline_user_data_job_failure_reason_pb);
var google_ads_googleads_v3_enums_offline_user_data_job_status_pb = require('../../../../../google/ads/googleads/v3/enums/offline_user_data_job_status_pb.js');
goog.object.extend(proto, google_ads_googleads_v3_enums_offline_user_data_job_status_pb);
var google_ads_googleads_v3_enums_offline_user_data_job_type_pb = require('../../../../../google/ads/googleads/v3/enums/offline_user_data_job_type_pb.js');
goog.object.extend(proto, google_ads_googleads_v3_enums_offline_user_data_job_type_pb);
var google_api_field_behavior_pb = require('../../../../../google/api/field_behavior_pb.js');
goog.object.extend(proto, google_api_field_behavior_pb);
var google_api_resource_pb = require('../../../../../google/api/resource_pb.js');
goog.object.extend(proto, google_api_resource_pb);
var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.object.extend(proto, google_protobuf_wrappers_pb);
var google_api_annotations_pb = require('../../../../../google/api/annotations_pb.js');
goog.object.extend(proto, google_api_annotations_pb);
goog.exportSymbol('proto.google.ads.googleads.v3.resources.OfflineUserDataJob', null, global);
goog.exportSymbol('proto.google.ads.googleads.v3.resources.OfflineUserDataJob.MetadataCase', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.ads.googleads.v3.resources.OfflineUserDataJob = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.google.ads.googleads.v3.resources.OfflineUserDataJob.oneofGroups_);
};
goog.inherits(proto.google.ads.googleads.v3.resources.OfflineUserDataJob, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.ads.googleads.v3.resources.OfflineUserDataJob.displayName = 'proto.google.ads.googleads.v3.resources.OfflineUserDataJob';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.google.ads.googleads.v3.resources.OfflineUserDataJob.oneofGroups_ = [[7,8]];

/**
 * @enum {number}
 */
proto.google.ads.googleads.v3.resources.OfflineUserDataJob.MetadataCase = {
  METADATA_NOT_SET: 0,
  CUSTOMER_MATCH_USER_LIST_METADATA: 7,
  STORE_SALES_METADATA: 8
};

/**
 * @return {proto.google.ads.googleads.v3.resources.OfflineUserDataJob.MetadataCase}
 */
proto.google.ads.googleads.v3.resources.OfflineUserDataJob.prototype.getMetadataCase = function() {
  return /** @type {proto.google.ads.googleads.v3.resources.OfflineUserDataJob.MetadataCase} */(jspb.Message.computeOneofCase(this, proto.google.ads.googleads.v3.resources.OfflineUserDataJob.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.ads.googleads.v3.resources.OfflineUserDataJob.prototype.toObject = function(opt_includeInstance) {
  return proto.google.ads.googleads.v3.resources.OfflineUserDataJob.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.ads.googleads.v3.resources.OfflineUserDataJob} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.ads.googleads.v3.resources.OfflineUserDataJob.toObject = function(includeInstance, msg) {
  var f, obj = {
    resourceName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    id: (f = msg.getId()) && google_protobuf_wrappers_pb.Int64Value.toObject(includeInstance, f),
    externalId: (f = msg.getExternalId()) && google_protobuf_wrappers_pb.Int64Value.toObject(includeInstance, f),
    type: jspb.Message.getFieldWithDefault(msg, 4, 0),
    status: jspb.Message.getFieldWithDefault(msg, 5, 0),
    failureReason: jspb.Message.getFieldWithDefault(msg, 6, 0),
    customerMatchUserListMetadata: (f = msg.getCustomerMatchUserListMetadata()) && google_ads_googleads_v3_common_offline_user_data_pb.CustomerMatchUserListMetadata.toObject(includeInstance, f),
    storeSalesMetadata: (f = msg.getStoreSalesMetadata()) && google_ads_googleads_v3_common_offline_user_data_pb.StoreSalesMetadata.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.ads.googleads.v3.resources.OfflineUserDataJob}
 */
proto.google.ads.googleads.v3.resources.OfflineUserDataJob.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.ads.googleads.v3.resources.OfflineUserDataJob;
  return proto.google.ads.googleads.v3.resources.OfflineUserDataJob.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.ads.googleads.v3.resources.OfflineUserDataJob} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.ads.googleads.v3.resources.OfflineUserDataJob}
 */
proto.google.ads.googleads.v3.resources.OfflineUserDataJob.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setResourceName(value);
      break;
    case 2:
      var value = new google_protobuf_wrappers_pb.Int64Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.Int64Value.deserializeBinaryFromReader);
      msg.setId(value);
      break;
    case 3:
      var value = new google_protobuf_wrappers_pb.Int64Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.Int64Value.deserializeBinaryFromReader);
      msg.setExternalId(value);
      break;
    case 4:
      var value = /** @type {!proto.google.ads.googleads.v3.enums.OfflineUserDataJobTypeEnum.OfflineUserDataJobType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 5:
      var value = /** @type {!proto.google.ads.googleads.v3.enums.OfflineUserDataJobStatusEnum.OfflineUserDataJobStatus} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    case 6:
      var value = /** @type {!proto.google.ads.googleads.v3.enums.OfflineUserDataJobFailureReasonEnum.OfflineUserDataJobFailureReason} */ (reader.readEnum());
      msg.setFailureReason(value);
      break;
    case 7:
      var value = new google_ads_googleads_v3_common_offline_user_data_pb.CustomerMatchUserListMetadata;
      reader.readMessage(value,google_ads_googleads_v3_common_offline_user_data_pb.CustomerMatchUserListMetadata.deserializeBinaryFromReader);
      msg.setCustomerMatchUserListMetadata(value);
      break;
    case 8:
      var value = new google_ads_googleads_v3_common_offline_user_data_pb.StoreSalesMetadata;
      reader.readMessage(value,google_ads_googleads_v3_common_offline_user_data_pb.StoreSalesMetadata.deserializeBinaryFromReader);
      msg.setStoreSalesMetadata(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.ads.googleads.v3.resources.OfflineUserDataJob.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.ads.googleads.v3.resources.OfflineUserDataJob.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.ads.googleads.v3.resources.OfflineUserDataJob} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.ads.googleads.v3.resources.OfflineUserDataJob.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getResourceName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getId();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_wrappers_pb.Int64Value.serializeBinaryToWriter
    );
  }
  f = message.getExternalId();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_wrappers_pb.Int64Value.serializeBinaryToWriter
    );
  }
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
  f = message.getFailureReason();
  if (f !== 0.0) {
    writer.writeEnum(
      6,
      f
    );
  }
  f = message.getCustomerMatchUserListMetadata();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      google_ads_googleads_v3_common_offline_user_data_pb.CustomerMatchUserListMetadata.serializeBinaryToWriter
    );
  }
  f = message.getStoreSalesMetadata();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      google_ads_googleads_v3_common_offline_user_data_pb.StoreSalesMetadata.serializeBinaryToWriter
    );
  }
};


/**
 * optional string resource_name = 1;
 * @return {string}
 */
proto.google.ads.googleads.v3.resources.OfflineUserDataJob.prototype.getResourceName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.ads.googleads.v3.resources.OfflineUserDataJob} returns this
 */
proto.google.ads.googleads.v3.resources.OfflineUserDataJob.prototype.setResourceName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional google.protobuf.Int64Value id = 2;
 * @return {?proto.google.protobuf.Int64Value}
 */
proto.google.ads.googleads.v3.resources.OfflineUserDataJob.prototype.getId = function() {
  return /** @type{?proto.google.protobuf.Int64Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.Int64Value, 2));
};


/**
 * @param {?proto.google.protobuf.Int64Value|undefined} value
 * @return {!proto.google.ads.googleads.v3.resources.OfflineUserDataJob} returns this
*/
proto.google.ads.googleads.v3.resources.OfflineUserDataJob.prototype.setId = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.ads.googleads.v3.resources.OfflineUserDataJob} returns this
 */
proto.google.ads.googleads.v3.resources.OfflineUserDataJob.prototype.clearId = function() {
  return this.setId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.ads.googleads.v3.resources.OfflineUserDataJob.prototype.hasId = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.Int64Value external_id = 3;
 * @return {?proto.google.protobuf.Int64Value}
 */
proto.google.ads.googleads.v3.resources.OfflineUserDataJob.prototype.getExternalId = function() {
  return /** @type{?proto.google.protobuf.Int64Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.Int64Value, 3));
};


/**
 * @param {?proto.google.protobuf.Int64Value|undefined} value
 * @return {!proto.google.ads.googleads.v3.resources.OfflineUserDataJob} returns this
*/
proto.google.ads.googleads.v3.resources.OfflineUserDataJob.prototype.setExternalId = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.ads.googleads.v3.resources.OfflineUserDataJob} returns this
 */
proto.google.ads.googleads.v3.resources.OfflineUserDataJob.prototype.clearExternalId = function() {
  return this.setExternalId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.ads.googleads.v3.resources.OfflineUserDataJob.prototype.hasExternalId = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional google.ads.googleads.v3.enums.OfflineUserDataJobTypeEnum.OfflineUserDataJobType type = 4;
 * @return {!proto.google.ads.googleads.v3.enums.OfflineUserDataJobTypeEnum.OfflineUserDataJobType}
 */
proto.google.ads.googleads.v3.resources.OfflineUserDataJob.prototype.getType = function() {
  return /** @type {!proto.google.ads.googleads.v3.enums.OfflineUserDataJobTypeEnum.OfflineUserDataJobType} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.google.ads.googleads.v3.enums.OfflineUserDataJobTypeEnum.OfflineUserDataJobType} value
 * @return {!proto.google.ads.googleads.v3.resources.OfflineUserDataJob} returns this
 */
proto.google.ads.googleads.v3.resources.OfflineUserDataJob.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional google.ads.googleads.v3.enums.OfflineUserDataJobStatusEnum.OfflineUserDataJobStatus status = 5;
 * @return {!proto.google.ads.googleads.v3.enums.OfflineUserDataJobStatusEnum.OfflineUserDataJobStatus}
 */
proto.google.ads.googleads.v3.resources.OfflineUserDataJob.prototype.getStatus = function() {
  return /** @type {!proto.google.ads.googleads.v3.enums.OfflineUserDataJobStatusEnum.OfflineUserDataJobStatus} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {!proto.google.ads.googleads.v3.enums.OfflineUserDataJobStatusEnum.OfflineUserDataJobStatus} value
 * @return {!proto.google.ads.googleads.v3.resources.OfflineUserDataJob} returns this
 */
proto.google.ads.googleads.v3.resources.OfflineUserDataJob.prototype.setStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 5, value);
};


/**
 * optional google.ads.googleads.v3.enums.OfflineUserDataJobFailureReasonEnum.OfflineUserDataJobFailureReason failure_reason = 6;
 * @return {!proto.google.ads.googleads.v3.enums.OfflineUserDataJobFailureReasonEnum.OfflineUserDataJobFailureReason}
 */
proto.google.ads.googleads.v3.resources.OfflineUserDataJob.prototype.getFailureReason = function() {
  return /** @type {!proto.google.ads.googleads.v3.enums.OfflineUserDataJobFailureReasonEnum.OfflineUserDataJobFailureReason} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {!proto.google.ads.googleads.v3.enums.OfflineUserDataJobFailureReasonEnum.OfflineUserDataJobFailureReason} value
 * @return {!proto.google.ads.googleads.v3.resources.OfflineUserDataJob} returns this
 */
proto.google.ads.googleads.v3.resources.OfflineUserDataJob.prototype.setFailureReason = function(value) {
  return jspb.Message.setProto3EnumField(this, 6, value);
};


/**
 * optional google.ads.googleads.v3.common.CustomerMatchUserListMetadata customer_match_user_list_metadata = 7;
 * @return {?proto.google.ads.googleads.v3.common.CustomerMatchUserListMetadata}
 */
proto.google.ads.googleads.v3.resources.OfflineUserDataJob.prototype.getCustomerMatchUserListMetadata = function() {
  return /** @type{?proto.google.ads.googleads.v3.common.CustomerMatchUserListMetadata} */ (
    jspb.Message.getWrapperField(this, google_ads_googleads_v3_common_offline_user_data_pb.CustomerMatchUserListMetadata, 7));
};


/**
 * @param {?proto.google.ads.googleads.v3.common.CustomerMatchUserListMetadata|undefined} value
 * @return {!proto.google.ads.googleads.v3.resources.OfflineUserDataJob} returns this
*/
proto.google.ads.googleads.v3.resources.OfflineUserDataJob.prototype.setCustomerMatchUserListMetadata = function(value) {
  return jspb.Message.setOneofWrapperField(this, 7, proto.google.ads.googleads.v3.resources.OfflineUserDataJob.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.ads.googleads.v3.resources.OfflineUserDataJob} returns this
 */
proto.google.ads.googleads.v3.resources.OfflineUserDataJob.prototype.clearCustomerMatchUserListMetadata = function() {
  return this.setCustomerMatchUserListMetadata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.ads.googleads.v3.resources.OfflineUserDataJob.prototype.hasCustomerMatchUserListMetadata = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional google.ads.googleads.v3.common.StoreSalesMetadata store_sales_metadata = 8;
 * @return {?proto.google.ads.googleads.v3.common.StoreSalesMetadata}
 */
proto.google.ads.googleads.v3.resources.OfflineUserDataJob.prototype.getStoreSalesMetadata = function() {
  return /** @type{?proto.google.ads.googleads.v3.common.StoreSalesMetadata} */ (
    jspb.Message.getWrapperField(this, google_ads_googleads_v3_common_offline_user_data_pb.StoreSalesMetadata, 8));
};


/**
 * @param {?proto.google.ads.googleads.v3.common.StoreSalesMetadata|undefined} value
 * @return {!proto.google.ads.googleads.v3.resources.OfflineUserDataJob} returns this
*/
proto.google.ads.googleads.v3.resources.OfflineUserDataJob.prototype.setStoreSalesMetadata = function(value) {
  return jspb.Message.setOneofWrapperField(this, 8, proto.google.ads.googleads.v3.resources.OfflineUserDataJob.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.ads.googleads.v3.resources.OfflineUserDataJob} returns this
 */
proto.google.ads.googleads.v3.resources.OfflineUserDataJob.prototype.clearStoreSalesMetadata = function() {
  return this.setStoreSalesMetadata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.ads.googleads.v3.resources.OfflineUserDataJob.prototype.hasStoreSalesMetadata = function() {
  return jspb.Message.getField(this, 8) != null;
};


goog.object.extend(exports, proto.google.ads.googleads.v3.resources);
